# .github/workflows/test.yml
name: Run Tests

on:
  push:
    branches:
      - main  # Cambia esto a tu rama principal si es diferente
  pull_request:
    branches:
      - main  # Cambia esto a tu rama principal si es diferente

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Usa la versión de Node.js que necesitas

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test -- --coverage
      env:
        CI: true  # Configura el entorno como CI para algunas herramientas de testing
